# NaturalCompass Configuration

search:
  timeout: 5s
  tiers:
    tier1: 1000
    tier2: 2500
    tier3: 5000
    tier4: 10000
    tier5: 25000
display:
  show-coordinates: true
  messages:
    searching: true
    found: true
logging:
  debug: false
  detaillogging: true # Added for detailed bug reports
biomes:
  excluded: []
recipes:
  enabled: true